name: publish

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Sync caddy and builder versions
        id: set_version
        run: |
          VERSION=$(gawk 'match($0, /.*caiych\/caddy:(.*)/, a) {print a[1];}' Dockerfile) &&
          echo $VERSION &&
          echo "::set-output name=version::$VERSION"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: caiych/caiych-caddy:${{ steps.set_version.outputs.version }}, caiych/caiych-caddy:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
