name: publish

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.16'

      - 
        name: Get sync caddy version
        run: go get github.com/caiych/sync-caddy-version

      - 
        name: Sync caddy and builder versions
        id: sync_versions
        run: |
          VERSION=$($HOME/go/bin/sync-caddy-version --input="$(pwd)/raw/Dockerfile" --output="$(pwd)/Dockerfile" --version_placeholder=VERSION --output_used_version_to_stdout) &&
          echo $VERSION &&
          echo "::set-output name=version::$VERSION"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: caiych/caiych-caddy:${{ steps.sync_versions.outputs.version }}, caiych/caiych-caddy:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
